spring.application.name=PokemonDB

# 1. Database Connection (Render PostgreSQL)
# psql ????? ??? ???? DB?? ?????.
spring.datasource.url=jdbc:postgresql://dpg-d6le8j1aae7s7386ckvg-a.singapore-postgres.render.com/poke_lula
spring.datasource.username=poke_lula_user
spring.datasource.password=wBvABdfxvuw7gEZt49HOuPe3zVTvZcla
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA/Hibernate ??
# ?? ???? ?? ?? 'create'? ???? ????, ???? 'update'? ?????.
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect